/**
 * Copies the files a site needs to read profile.json into its source tree:
 * the hand-written types, the JSON Schema, and a self-contained markup module
 * (parser + HTML + plain printers).
 *
 *   bun scripts/vendor.ts <destination directory>
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, resolve } from 'node:path';

const ROOT = join(import.meta.dir, '..');
if (!process.argv[2]) {
	console.error('usage: bun scripts/vendor.ts <destination directory>');
	process.exit(2);
}
const dest = resolve(process.argv[2]);
if (!existsSync(dest)) {
	console.error(`destination does not exist: ${dest}`);
	process.exit(2);
}
let sha = 'unknown';
try {
	sha = execSync('git rev-parse --short HEAD', { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] })
		.toString()
		.trim();
} catch {}
const header = `// Generated by resume-builder@${sha} (scripts/vendor.ts). Do not edit here.\n`;

function bundleMarkup(): string {
	const parse = readFileSync(join(ROOT, 'src/lib/core/markup/parse.ts'), 'utf8');
	const html = readFileSync(join(ROOT, 'src/lib/core/markup/html.ts'), 'utf8').replace(
		/^import .*\n/gm,
		''
	);
	const plain = readFileSync(join(ROOT, 'src/lib/core/markup/plain.ts'), 'utf8').replace(
		/^import .*\n/gm,
		''
	);
	return `${header}\n${parse}\n${html}\n${plain}`;
}

mkdirSync(dest, { recursive: true });
writeFileSync(
	join(dest, 'profile.types.ts'),
	header + readFileSync(join(ROOT, 'src/lib/core/schema/types.ts'), 'utf8')
);
writeFileSync(
	join(dest, 'profile.schema.json'),
	readFileSync(join(ROOT, 'schema/profile-1.json'), 'utf8')
);
writeFileSync(join(dest, 'markup.ts'), bundleMarkup());
console.log(`vendored profile.types.ts, profile.schema.json, markup.ts → ${dest}`);
